## 1. Import Necessary Libraries

In [17]:
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score

## 2. Import Dataset

In [13]:
breast_cancer_data = datasets.load_breast_cancer()
breast_cancer_data_df = pd.DataFrame( data=breast_cancer_data.data,columns = breast_cancer_data["feature_names"])
breast_cancer_data_df["Target"] = breast_cancer_data.target
breast_cancer_data_df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,Target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

## 3. Data Understanding

In [14]:
breast_cancer_data_df.shape

(569, 31)

In [15]:
breast_cancer_data_df.isna().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
Target                     0
dtype: int64

In [16]:
breast_cancer_data_df.dtypes

mean radius                float64
mean texture               float64
mean perimeter             float64
mean area                  float64
mean smoothness            float64
mean compactness           float64
mean concavity             float64
mean concave points        float64
mean symmetry              float64
mean fractal dimension     float64
radius error               float64
texture error              float64
perimeter error            float64
area error                 float64
smoothness error           float64
compactness error          float64
concavity error            float64
concave points error       float64
symmetry error             float64
fractal dimension error    float64
worst radius               float64
worst texture              float64
worst perimeter            float64
worst area                 float64
worst smoothness           float64
worst compactness          float64
worst concavity            float64
worst concave points       float64
worst symmetry             float64
worst fractal dimension    float64
Target                       int32
dtype: object

## 4. Data Preparation

In [19]:
X = breast_cancer_data_df.drop("Target",axis = 1)

In [22]:
std_scaler = StandardScaler()
scaled_x = pd.DataFrame(std_scaler.fit_transform(X))
scaled_x.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,1.097064,-2.073335,1.269934,0.984375,1.568466,3.283515,2.652874,2.532475,2.217515,2.255747,...,1.886690,-1.359293,2.303601,2.001237,1.307686,2.616665,2.109526,2.296076,2.750622,1.937015
1,1.829821,-0.353632,1.685955,1.908708,-0.826962,-0.487072,-0.023846,0.548144,0.001392,-0.868652,...,1.805927,-0.369203,1.535126,1.890489,-0.375612,-0.430444,-0.146749,1.087084,-0.243890,0.281190
2,1.579888,0.456187,1.566503,1.558884,0.942210,1.052926,1.363478,2.037231,0.939685,-0.398008,...,1.511870,-0.023974,1.347475,1.456285,0.527407,1.082932,0.854974,1.955000,1.152255,0.201391
3,-0.768909,0.253732,-0.592687,-0.764464,3.283553,3.402909,1.915897,1.451707,2.867383,4.910919,...,-0.281464,0.133984,-0.249939,-0.550021,3.394275,3.893397,1.989588,2.175786,6.046041,4.935010
4,1.750297,-1.151816,1.776573,1.826229,0.280372,0.539340,1.371011,1.428493,-0.009560,-0.562450,...,1.298575,-1.466770,1.338539,1.220724,0.220556,-0.313395,0.613179,0.729259,-0.868353,-0.397100

In [23]:
y = breast_cancer_data_df["Target"]

## 5. Model Building

In [26]:
X_train, X_test, y_train, y_test = train_test_split(scaled_x,y,test_size=0.20,random_state=12, shuffle=True,stratify=y)

In [27]:
print(X_train.shape,y_train.shape)

(455, 30) (455,)

In [28]:
print(X_test.shape, y_test.shape)

(114, 30) (114,)

In [35]:
gradient_boosting_classifier = GradientBoostingClassifier(n_estimators=50,max_depth=3)

## 6. Model Training

In [36]:
gradient_boosting_classifier.fit(scaled_x,y)

GradientBoostingClassifier(n_estimators=50)

## 7. Model Testing || 8. Model Evaluation

In [37]:
y_pred_train = gradient_boosting_classifier.predict(X_train)
print("Confustion Matrix:\n", confusion_matrix(y_train,y_pred_train))
print("Accuracy Score:", accuracy_score(y_train,y_pred_train))
print("Precision Score:", precision_score(y_train,y_pred_train))
print("Recall Score:", recall_score(y_train,y_pred_train))

Confustion Matrix:
 [[170   0]
 [  0 285]]
Accuracy Score: 1.0
Precision Score: 1.0
Recall Score: 1.0

In [38]:
y_pred_test = gradient_boosting_classifier.predict(X_test)
print("Confustion Matrix:\n", confusion_matrix(y_test,y_pred_test))
print("Accuracy Score:", accuracy_score(y_test,y_pred_test))
print("Precision Score:", precision_score(y_test,y_pred_test))
print("Recall Score:", recall_score(y_test,y_pred_test))

Confustion Matrix:
 [[41  1]
 [ 0 72]]
Accuracy Score: 0.9912280701754386
Precision Score: 0.9863013698630136
Recall Score: 1.0

## 9. Model Deployment

In [39]:
from pickle import dump

In [40]:
dump(gradient_boosting_classifier,open("GBM.pkl","wb"))

### The End!!!