### Import necessary libraries

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,auc,roc_auc_score,roc_curve

#### import dataset

In [8]:
credit_card_data = pd.read_csv("credit_card_clean.csv")
credit_card_data

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,1,20000.0,female,university,married,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,female,university,single,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,female,university,single,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,female,university,married,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,male,university,married,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000.0,male,highschool,married,39,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,29997,150000.0,male,highschool,single,43,-1,-1,-1,-1,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,29998,30000.0,male,university,single,37,4,3,2,-1,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,29999,80000.0,male,highschool,married,41,1,-1,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,30000,50000.0,male,university,married,46,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

### data understanding

In [9]:
credit_card_data.shape

(30000, 25)

In [10]:
credit_card_data.isna().sum()

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_1        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
DEFAULT      0
dtype: int64

In [11]:
credit_card_data.dtypes

ID             int64
LIMIT_BAL    float64
SEX           object
EDUCATION     object
MARRIAGE      object
AGE            int64
PAY_1          int64
PAY_2          int64
PAY_3          int64
PAY_4          int64
PAY_5          int64
PAY_6          int64
BILL_AMT1    float64
BILL_AMT2    float64
BILL_AMT3    float64
BILL_AMT4    float64
BILL_AMT5    float64
BILL_AMT6    float64
PAY_AMT1     float64
PAY_AMT2     float64
PAY_AMT3     float64
PAY_AMT4     float64
PAY_AMT5     float64
PAY_AMT6     float64
DEFAULT        int64
dtype: object

### DATA PREPARATION

In [15]:
del credit_card_data["ID"]

In [16]:
credit_card_data

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,20000.0,female,university,married,24,2,2,-1,-1,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,female,university,single,26,-1,2,0,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,female,university,single,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,female,university,married,37,0,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,male,university,married,57,-1,0,-1,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,male,highschool,married,39,0,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,150000.0,male,highschool,single,43,-1,-1,-1,-1,0,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,30000.0,male,university,single,37,4,3,2,-1,0,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,80000.0,male,highschool,married,41,1,-1,0,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,50000.0,male,university,married,46,0,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

In [17]:
le = LabelEncoder()
credit_card_data["SEX"] = le.fit_transform(credit_card_data["SEX"])
credit_card_data["EDUCATION"] = le.fit_transform(credit_card_data["EDUCATION"])
credit_card_data["MARRIAGE"] = le.fit_transform(credit_card_data["MARRIAGE"])

In [19]:
credit_card_data

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,20000.0,0,3,0,24,2,2,-1,-1,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,0,3,2,26,-1,2,0,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,0,3,2,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,0,3,0,37,0,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,1,3,0,57,-1,0,-1,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,1,1,0,39,0,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,150000.0,1,1,2,43,-1,-1,-1,-1,0,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,30000.0,1,3,2,37,4,3,2,-1,0,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,80000.0,1,1,0,41,1,-1,0,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,50000.0,1,3,0,46,0,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

In [23]:
credit_card_data.dtypes

LIMIT_BAL    float64
SEX            int32
EDUCATION      int32
MARRIAGE       int32
AGE            int64
PAY_1          int64
PAY_2          int64
PAY_3          int64
PAY_4          int64
PAY_5          int64
PAY_6          int64
BILL_AMT1    float64
BILL_AMT2    float64
BILL_AMT3    float64
BILL_AMT4    float64
BILL_AMT5    float64
BILL_AMT6    float64
PAY_AMT1     float64
PAY_AMT2     float64
PAY_AMT3     float64
PAY_AMT4     float64
PAY_AMT5     float64
PAY_AMT6     float64
DEFAULT        int64
dtype: object

In [21]:
X = credit_card_data.drop("DEFAULT", axis = 1)
y = credit_card_data["DEFAULT"]

### Model Building

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, shuffle=True, random_state=12, stratify=y)

In [25]:
X_train.shape,y_train.shape

((24000, 23), (24000,))

In [26]:
X_test.shape,y_test.shape

((6000, 23), (6000,))

### model training

In [27]:
adaboost_classifier = AdaBoostClassifier()
gradient_boost_classifier = GradientBoostingClassifier(n_estimators=50)
xgbm_classifier = XGBClassifier(n_estimators=50)
lgbm_classifier = LGBMClassifier(n_estimators=50)

### model testing

#### training data

In [32]:
%%time
adaboost_classifier.fit(X_train,y_train)

CPU times: total: 3.03 s
Wall time: 3.13 s

AdaBoostClassifier()

In [33]:
%%time
gradient_boost_classifier.fit(X_train,y_train)

CPU times: total: 7.22 s
Wall time: 8.25 s

GradientBoostingClassifier(n_estimators=50)

In [34]:
%%time
xgbm_classifier.fit(X_train,y_train)

CPU times: total: 859 ms
Wall time: 286 ms

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=50,
              n_jobs=None, num_parallel_tree=None, ...)

In [35]:
%%time
lgbm_classifier.fit(X_train,y_train)

[LightGBM] [Info] Number of positive: 5309, number of negative: 18691
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004815 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3260
[LightGBM] [Info] Number of data points in the train set: 24000, number of used features: 23
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.221208 -> initscore=-1.258639
[LightGBM] [Info] Start training from score -1.258639
CPU times: total: 734 ms
Wall time: 295 ms

LGBMClassifier(n_estimators=50)

#### AdaBoost Classifier

##### Training data

In [45]:
y_pred_ada_train = adaboost_classifier.predict(X_train)

print("Confusion Matrix:\n", confusion_matrix(y_train,y_pred_ada_train))
print("Accuracy Score:"  ,accuracy_score(y_train,y_pred_ada_train))
print("Precision Score:" ,precision_score(y_train,y_pred_ada_train))
print("Recall Score:", recall_score(y_train,y_pred_ada_train))

Confusion Matrix:
 [[17883   808]
 [ 3539  1770]]
Accuracy Score: 0.818875
Precision Score: 0.6865787432117921
Recall Score: 0.33339611979657185

##### Testing data

In [47]:
y_pred_ada_test = adaboost_classifier.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(y_test,y_pred_ada_test))
print("Accuracy Score:"  ,accuracy_score(y_test,y_pred_ada_test))
print("Precision Score:" ,precision_score(y_test,y_pred_ada_test))
print("Recall Score:", recall_score(y_test,y_pred_ada_test))

Confusion Matrix:
 [[4479  194]
 [ 880  447]]
Accuracy Score: 0.821
Precision Score: 0.6973478939157566
Recall Score: 0.33685003767897514

#### Gradient Boost Classifier

In [48]:
y_pred_gbm_train  = gradient_boost_classifier.predict(X_train)
print("Confusion Matrix:\n", confusion_matrix(y_train,y_pred_gbm_train))
print("Accuracy Score:"  ,accuracy_score(y_train,y_pred_gbm_train))
print("Precision Score:" ,precision_score(y_train,y_pred_gbm_train))
print("Recall Score:", recall_score(y_train,y_pred_gbm_train))

Confusion Matrix:
 [[17807   884]
 [ 3361  1948]]
Accuracy Score: 0.823125
Precision Score: 0.6878531073446328
Recall Score: 0.3669240911659446

In [49]:
y_pred_gbm_test = gradient_boost_classifier.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(y_test,y_pred_gbm_test))
print("Accuracy Score:"  ,accuracy_score(y_test,y_pred_gbm_test))
print("Precision Score:" ,precision_score(y_test,y_pred_gbm_test))
print("Recall Score:", recall_score(y_test,y_pred_gbm_test))

Confusion Matrix:
 [[4469  204]
 [ 847  480]]
Accuracy Score: 0.8248333333333333
Precision Score: 0.7017543859649122
Recall Score: 0.3617181612660136

#### XGBM Classifier

##### Training data

In [50]:
y_pred_xgbm_train = xgbm_classifier.predict(X_train)
print("Confusion Matrix:\n", confusion_matrix(y_train,y_pred_xgbm_train))
print("Accuracy Score:"  ,accuracy_score(y_train,y_pred_xgbm_train))
print("Precision Score:" ,precision_score(y_train,y_pred_xgbm_train))
print("Recall Score:", recall_score(y_train,y_pred_xgbm_train))

Confusion Matrix:
 [[18124   567]
 [ 2759  2550]]
Accuracy Score: 0.8614166666666667
Precision Score: 0.8180943214629451
Recall Score: 0.48031644377472216

##### Testing data

In [51]:
y_pred_xgbm_test = xgbm_classifier.predict(X_test)
print("Confusion Matrix:\n", confusion_matrix(y_test,y_pred_xgbm_test))
print("Accuracy Score:"  ,accuracy_score(y_test,y_pred_xgbm_test))
print("Precision Score:" ,precision_score(y_test,y_pred_xgbm_test))
print("Recall Score:", recall_score(y_test,y_pred_xgbm_test))

Confusion Matrix:
 [[4425  248]
 [ 834  493]]
Accuracy Score: 0.8196666666666667
Precision Score: 0.6653171390013495
Recall Score: 0.3715146948003014

#### LGBM Classifier

In [54]:
y_pred_lgbm_train = lgbm_classifier.predict(X_train)

print("Confusion Matrix:\n", confusion_matrix(y_train,y_pred_lgbm_train))
print("Accuracy Score:"  ,accuracy_score(y_train,y_pred_lgbm_train))
print("Precision Score:" ,precision_score(y_train,y_pred_lgbm_train))
print("Recall Score:", recall_score(y_train,y_pred_lgbm_train))

Confusion Matrix:
 [[17888   803]
 [ 3243  2066]]
Accuracy Score: 0.8314166666666667
Precision Score: 0.7201115371209481
Recall Score: 0.38915049915238276

In [56]:
y_pred_lgbm_test = lgbm_classifier.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(y_test,y_pred_lgbm_test))
print("Accuracy Score:"  ,accuracy_score(y_test,y_pred_lgbm_test))
print("Precision Score:" ,precision_score(y_test,y_pred_lgbm_test))
print("Recall Score:", recall_score(y_test,y_pred_lgbm_test))

Confusion Matrix:
 [[4456  217]
 [ 841  486]]
Accuracy Score: 0.8236666666666667
Precision Score: 0.6913229018492176
Recall Score: 0.36623963828183875